language: node_js
node_js:
  - "node"
before_script:
  - npm install -g jest
  - cp .env-sample .env
  - mongo plfollowers-test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
services: 
  - mongodb
  - redis-server
env:
  - REDIS_URL=redis://localhost:6379